### ISSUE TITLE
Cannot start service

### ISSUE THREAD

**Issue by SergiuCip** [thias/puppet-lsyncd#1]
Hi there,

Thank you for creating such module, it is really useful.

I am trying to use your module and the install and configuration process it works as it should, however, when Puppet finishes and tries to re-(start) the service I am getting this error:

Error: Could not start Service[lsyncd]: Execution of '/sbin/service lsyncd start' returned 1: Starting lsyncd: Error: error preparing /etc/lsyncd.conf: /etc/lsyncd.conf:97: Invalid 'syncid' parameter: /etc/csync2/csync2_tmp1.cfg: No such file or directory
[FAILED]

Do you know why I might be getting this error?

Thank you,

Regards,
Cip

**Comment by thias** [comment]
As you might have noticed, this module doesn't really intend to take care of the lsyncd configuration. With the included template, I'm using lsyncd 2.1.5. If you're using an older or newer version, that could explain as lsyncd has usually undergone major changes with each release.

In any case, what you need to do is make sure you have a configuration that works with your lsyncd version, and only once that is done my module will help you deploy it uniformly and restart lsyncd when you push changes to it.

Your error message is way beyond the scope of this module, sorry.
